# Generated by Django 3.0 on 2020-01-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='facultyreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('fid', models.IntegerField()),
                ('address', models.CharField(default='', max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('stdid', models.IntegerField()),
                ('year', models.IntegerField(default=2017)),
                ('address', models.CharField(default='', max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(default='', max_length=10)),
                ('branch', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
