# Generated by Django 3.0 on 2020-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='atta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('stdid', models.IntegerField()),
                ('firstp', models.CharField(default='', max_length=50)),
                ('secondp', models.CharField(max_length=20)),
                ('thirdp', models.CharField(default='', max_length=10)),
                ('fourthp', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
