# Generated by Django 3.0 on 2020-01-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0002_atta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atta',
            name='firstp',
            field=models.CharField(blank='True', default='', max_length=10, null='True'),
        ),
        migrations.AlterField(
            model_name='atta',
            name='secondp',
            field=models.CharField(max_length=10),
        ),
    ]
