# Generated by Django 3.0 on 2020-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0004_auto_20200107_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atta',
            name='stdid',
            field=models.IntegerField(blank='True', null='True'),
        ),
    ]
