# Generated by Django 3.0 on 2020-01-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0005_auto_20200107_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('stdid', models.IntegerField(blank='True', null='True')),
                ('mark1', models.CharField(blank='True', default='', max_length=10, null='True')),
                ('mark2', models.CharField(max_length=10)),
                ('mark3', models.CharField(blank='True', default='', max_length=10, null='True')),
                ('per', models.CharField(blank='True', default='', max_length=10, null='True')),
            ],
        ),
    ]
