# Generated by Django 3.0 on 2020-01-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0006_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='per',
            field=models.CharField(default='', max_length=10),
        ),
    ]
