# Generated by Django 3.0 on 2020-01-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0007_auto_20200107_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='per',
        ),
    ]
