# Generated by Django 3.0 on 2020-01-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0008_remove_marks_per'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('stdid', models.IntegerField(blank='True', null='True')),
                ('fromdate', models.CharField(blank='True', default='', max_length=10, null='True')),
                ('todate', models.CharField(max_length=10)),
                ('status', models.CharField(blank='True', default='', max_length=10, null='True')),
            ],
        ),
    ]
