# Generated by Django 3.0 on 2020-01-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0010_auto_20200108_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyleave',
            name='reason',
            field=models.CharField(default='', max_length=20),
        ),
    ]
