# Generated by Django 3.0 on 2020-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0011_facultyleave_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentleavez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('stdid', models.IntegerField(blank='True', null='True')),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(default='', max_length=20)),
                ('status', models.CharField(blank='True', default='', max_length=10, null='True')),
            ],
        ),
    ]
