# Generated by Django 3.0 on 2020-01-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0012_studentleavez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyreg',
            name='fid',
            field=models.IntegerField(blank='True', null='True'),
        ),
    ]
