# Generated by Django 3.0 on 2020-01-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0013_auto_20200109_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyreg',
            name='address',
            field=models.CharField(blank='True', default='', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='facultyreg',
            name='email',
            field=models.CharField(blank='True', max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='facultyreg',
            name='mobile',
            field=models.IntegerField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='facultyreg',
            name='password',
            field=models.CharField(blank='True', default='', max_length=10, null='True'),
        ),
    ]
