# Generated by Django 3.0 on 2020-01-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0015_auto_20200109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyreg',
            name='email',
            field=models.CharField(max_length=20, null='True'),
        ),
    ]
