# Generated by Django 3.0 on 2020-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0016_auto_20200109_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyreg',
            name='password',
            field=models.CharField(max_length=10, null='True'),
        ),
    ]
